include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    unnecessary_underscores: ignore

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    use_super_parameters: true
